version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: English-Golang
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: english_ai_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  localstack:
      image: localstack/localstack
      environment:
        - SERVICES=s3
        - DEFAULT_REGION=us-east-1
      ports:
        - "4566:4566" # Edge port
      volumes:
        - "./localstack:/var/lib/localstack"
volumes:
  db_data:
